- name: install the nginx
  hosts: web
  become: yes # -b is the root user
  tasks:
  - name: install the nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
