# this is play level variable

- name: creating the variable
  hosts: localhost
  vars:     #play level variable
    NAME: "srikanth"
    PLACE: "kadapa"
    VILLAGE: "madakalavaripalle"
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "my name is {{NAME}} : iam from {{PLACE}} : village name : {{VILLAGE}}"