- name: multi level variables
  hosts: localhost
  vars:
    COURSE: "AWS DEVOPS"  #play level variables
    TRAINER: "SIVAKUMAR REDDY"
    DURATION: "120HR"
  tasks:
  - name: pring the information
    vars:
      COURSE: "jenkins"  #task level variables
      TRAINER: "siva"
      DURATION: 10hrs"
    ansible.builtin.debug:
      msg: "My course name is {{COURSE}} and traner is {{TRAINER}} and duration is {{DURATION}}"
    
