- name: inventory var vars_files
  hosts: localhost
  tasks:
  - name: print the information of inventory var vars_files
    ansible.builtin.debug:
      msg: "course: {{COURSE}} and trainer is {{TRAINER}} and Duration is {{DURATION}}"
      