- name: conditions
  hosts: localhost
  vars_prompt:
  - name: number
    prompt: enter the number?
    private: false
  tasks:
  - name: given number is lessthan 10
    ansible.builtin.debug:
      msg: "given number is lessthan {{number}}"
    when: number | int < 10
  
  - name: given number is greaterthan 10
    ansible.builtin.debug:
      msg: "given number is greaterthan {{number}} "
    when: number |  int >= 10