- name: default value
  hosts: localhost
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "location is {{location | default ('banglore')}}"

- name: uppercase
  hosts: localhost
  vars:
    wishes: "good morning namma bengaluru"
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "{{wishes | upper }}"

- name: lowercase
  hosts: localhost
  vars:
    wishes: "HAPPY BIRTHDAY TO ME"
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "{{wishes | lower }}"

# - name: dictionary to list
#   hosts: localhost
#   vars:
#    tools:
#       aws: 2
#       jenkins: 2
#       terraform: 2
#   tasks:
#   - name: 


- name: remove duplicate numbers
  hosts: localhost
  vars:
    numbers: [1,2,2,2,3,4,5]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "{{numbers | unique }}"
  
- name: min and max age
  hosts: localhost
  vars:
    ages: [ 23 65 12 67 54 87 100]
  tasks:
  - name: find the min ages
    ansible.builtin.debug:
      msg: "min ages are :{{ages | min}} and max ages are :{{ages | max}}"  
