- name: install the packages
  hosts: localhost
  become: yes
  tasks:
  - name: install the packages
    ansible.builtin.dnf:
      name: "{{item}}"
      state: latest
    loop:
    - mysql
    - git
    - nginx



- name: install the packages
  hosts: localhost
  become: yes
  tasks:
  - name: install the packages
    ansible.builtin.dnf:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - { name: 'mysql', state: 'absent'}
    - { name: 'git' , state: 'latest'}
    - { name: 'nginx', state: 'absent'}
