- name: create the db server
  hosts: db
  become: yes
  vars_prompt:
    - name: password
      prompt: What is your password?
      private: false
  tasks:
  - name: install the mysql server
    ansible.builtin.dnf:
      name: mysql-server
      state: latest
  - name: start and enable the service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: install the python dependies
    ansible.builtin.pip:
      name: 
      - mypysql
      - cr
  - name: check root setup or not
    community.mysql.mysql_info:
      login_user: "{{login_user}}"
      login_password: "{{password}}"
      login_host: "{{login_host}}"
      filter: version
    ignore_errors: yes
    register: mysql_output 

  

